In [1]:
import numpy as np
from pywindow import Molecule, MolecularSystem, Trajectory

In [2]:
trajectory = Trajectory()

In [3]:
history = trajectory.DLPOLY.load_HISTORY('./tests/test_5/HISTORY_CC3_cage')

In [4]:
frame_19 = history.get_frames(19)

In [5]:
frame_19

{'elements': array(['ni', 'ca', 'ca', 'cd', 'ct', 'ct', 'ct', 'ha', 'he', 'hc', 'hc',
        'hc', 'hc', 'hc', 'ni', 'ca', 'ca', 'cd', 'ct', 'ct', 'ct', 'ha',
        'he', 'hc', 'hc', 'hc', 'hc', 'hc', 'ni', 'ca', 'ca', 'cd', 'ct',
        'ct', 'ct', 'ha', 'he', 'hc', 'hc', 'hc', 'hc', 'hc', 'ni', 'ca',
        'ca', 'cd', 'ct', 'ct', 'ct', 'ha', 'he', 'hc', 'hc', 'hc', 'hc',
        'hc', 'ni', 'ca', 'ca', 'cd', 'ct', 'ct', 'ct', 'ha', 'he', 'hc',
        'hc', 'hc', 'hc', 'hc', 'ni', 'ca', 'ca', 'cd', 'ct', 'ct', 'ct',
        'ha', 'he', 'hc', 'hc', 'hc', 'hc', 'hc', 'ni', 'ca', 'ca', 'cd',
        'ct', 'ct', 'ct', 'ha', 'he', 'hc', 'hc', 'hc', 'hc', 'hc', 'ni',
        'ca', 'ca', 'cd', 'ct', 'ct', 'ct', 'ha', 'he', 'hc', 'hc', 'hc',
        'hc', 'hc', 'ni', 'ca', 'ca', 'cd', 'ct', 'ct', 'ct', 'ha', 'he',
        'hc', 'hc', 'hc', 'hc', 'hc', 'ni', 'ca', 'ca', 'cd', 'ct', 'ct',
        'ct', 'ha', 'he', 'hc', 'hc', 'hc', 'hc', 'hc', 'ni', 'ca', 'ca',
        'cd', 'ct', 'ct', 

In [6]:
molsys_19 = MolecularSystem().load_trajectory_frame(frame_19) 

In [7]:
molsys_19.swap_atom_keys({'he': 'h'})

In [8]:
molsys_19.decipher_atom_keys("opls")

In [9]:
molsys_19.separate_discrete_molecules()

In [10]:
mol_0 = molsys_19.molecules[0]

In [11]:
mol_0_com = mol_0.calculate_COM()

In [12]:
mol_0_maxd = mol_0.calculate_maximum_diameter()

In [13]:
mol_0_voidd = mol_0.calculate_void_diameter()

In [14]:
mol_0_voidV = mol_0.calculate_void_volume()

In [15]:
mol_0_voidd_opt = mol_0.calculate_void_diameter_opt()

In [16]:
mol_0_voidV_opt = mol_0.calculate_void_volume_opt()

In [17]:
mol_0.calculate_windows(void_opt=False)

Using void opt False


(array([ 3.87592996,  4.03483757,  3.94691343,  4.42654878]),
 array([[-1.40842683, -1.32564223,  1.86155575],
        [ 2.67967253,  2.08931914,  1.61790513],
        [-2.12261809,  1.71598578, -1.32886047],
        [ 1.60205355, -2.91408787, -2.81821651]]))

In [18]:
mol_0.calculate_windows(void_opt=True)

Using void opt True


(array([ 3.87746909,  4.1187237 ,  3.93179729,  3.88909279]),
 array([[-1.4518915 , -1.37643852,  1.93008862],
        [ 2.96599665,  2.27599079,  1.82248981],
        [-2.00916303,  1.61221437, -1.25484209],
        [ 0.99722229, -2.06805166, -1.99222515]]))

In [19]:
history.analysis(frames=19, forcefield='opls', swap_atoms={'he': 'h'})

KeyError: 'void_opt'

In [ ]:
for frame in range(history.no_of_frames):
    print('Frame {0}'.format(frame))
    print('COM     :', history.analysis(ncpus=4, frames=frame, forcefield='opls', swap_atoms={'he': 'h'}, void_opt=False)[0]['COM'])
    print('COM_opt :', history.analysis(ncpus=4, frames=frame, forcefield='opls', swap_atoms={'he': 'h'})[0]['COM'])
    print('Void    :', history.analysis(ncpus=4, frames=frame, forcefield='opls', swap_atoms={'he': 'h'}, void_opt=False)[0]['void_diameter'])
    print('Void_opt:', history.analysis(ncpus=4, frames=frame, forcefield='opls', swap_atoms={'he': 'h'})[0]['void_diameter_opt'])
    print('Void    :',frame, history.analysis(ncpus=4, frames=frame, forcefield='opls', swap_atoms={'he': 'h'}, void_opt=False)[0]['windows'][0])
    print('Void_opt:',frame, history.analysis(ncpus=4, frames=frame, forcefield='opls', swap_atoms={'he': 'h'})[0]['windows'][0])

In [ ]:
for frame in range(history.no_of_frames):
    molsys = MolecularSystem().load_trajectory_frame(history.get_frames(frame))
    molsys.swap_atom_keys('he', 'h')
    molsys.decipher_atom_keys("opls")
    molsys.dump_xyz("frame_{}".format(frame))